# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/golangci/golangci-lint
  rev: v1.50.0
  hooks:
  - id: golangci-lint
-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.5
    hooks:
    #
    # Go Mod Tidy
    #
    -   id: go-mod-tidy
    -   id: go-mod-tidy-repo
    #
    # Go Test
    #
    -   id: go-test-mod
    -   id: go-test-repo-mod
    #
    # Go Vet
    #
    -   id: go-vet
    -   id: go-vet-mod
    -   id: go-vet-repo-mod
    #
    # Revive
    #
    -   id: go-revive
    -   id: go-revive-mod
    -   id: go-revive-repo-mod
    #
    # GoSec
    #
    -   id: go-sec-mod
    -   id: go-sec-repo-mod
    #
    # StaticCheck
    #
    -   id: go-staticcheck-mod
    -   id: go-staticcheck-repo-mod
    #
    # Formatters
    #
    -   id: go-fmt
    -   id: go-fmt-repo
    -   id: go-fumpt        # replaces go-fmt
    -   id: go-fumpt-repo   # replaces go-fmt-repo
    -   id: go-imports      # replaces go-fmt
    -   id: go-imports-repo # replaces go-fmt-repo
    -   id: go-returns      # replaces go-imports & go-fmt
    -   id: go-returns-repo # replaces go-imports-repo & go-fmt-repo
    #
    # Style Checkers
    #
    -   id: go-lint
    -   id: go-critic
    #
    # GolangCI-Lint
    # - Fast Multi-Linter
    # - Can be configured to replace MOST other hooks
    # - Supports repo config file for configuration
    # - https://github.com/golangci/golangci-lint
    #
    -   id: golangci-lint
    -   id: golangci-lint-mod
    -   id: golangci-lint-repo-mod
