#!/usr/bin/python
from distutils.dir_util import copy_tree 
import os
import sys

GREENERY_PATH = os.path.join(os.path.expanduser('~'), '.greenery')

USAGE = '''
USAGE: water <target>
'''

if len(sys.argv) != 2:
    print(USAGE)

    sys.exit()

target = sys.argv[1]
path = os.path.join(GREENERY_PATH, target)

if os.path.isfile(target):
    with open(path, 'r') as input_file:
        with open(target, 'a') as output_file:
            for line in input_file:
                output_file.write(line)
elif os.path.isdir(target):
    copy_tree(path, target)
